### ISSUE TITLE
Converting a Dictionary to JSON

### ISSUE THREAD

**Issue by lucatorella** [bignerdranch/Freddy#133] opened 2016-02-13 19:03 UTC
Is there a easy way to convert a dictionary (i.e of type `[String : String]`, `[String, AnyObject]`,...) without writing all this boiler plate?

```
var tempDict: [String : JSON]
dict.forEach { k, v in
    if let v = v as? String {
        tempDict[k] = JSON.String(v)
    } else if let v = v as? Int {
        tempDict[k] = JSON.Int(v)
    } else if let v = v as? Bool {
        tempDict[k] = JSON.Bool(v)
    }
}
let json = JSON.Dictionary(tempDict)
```

If not should we add a new initializer?

**Comment by randomstep** [comment] 2016-02-15 13:28
I ran into this too. Going up a level, you can get that dictionary out but keep it a JSON value:
`try JSON(yourJSON.dictionary(keyForTempDictValue))`

Another option is to just guard that your value is a dictionary, but not unpack it, with something like:
`guard case .Dictionary = jsonvalueThatContainsTempDict`

There are other approaches, but I'd have to know a bit more about what problem you're trying to solve. In my case, we are using JSONAPI, so I needed the attributes dictionary out and did not like the repetition of indexing into `attributes` as part of my keypath for each property. I ended up going with the first solution, of re-wrapping the dictionary back into JSON.

**Comment by lucatorella** [comment] 2016-02-15 13:50
I'm not sure I understood what you said. Anyway the use case is that I have a dictionary and I want to create a JSON value. An easy example is: I have a dictionary in Core Data and I want to create a JSON value out of it.

**Comment by randomstep** [comment] 2016-02-15 14:19
Sorry, I misunderstood your question.

**Comment by jgallagher** [comment] 2016-02-15 14:22
I think what you're asking for is pretty similar to how we interface with `NSJSONSerialization`: https://github.com/bignerdranch/Freddy/blob/dc98e18c84418cc984e283b1836dcb1bd5324d68/Sources/JSONParsing.swift#L57-L77

We've had a few discussions about making an interface like that public. The problem is that it's really, really slow for large objects, and we don't really want to encourage people to use it. We addressed the `NSJSONSerialization` case by making `JSONParser` the default parser. Could you talk more about your use case? In particular, what do you mean by "I have a dictionary in Core Data"?

**Comment by lucatorella** [comment] 2016-02-15 15:37
So it's a very specific enterprise app, that user can customize with their own code written in JavaScript. One of the feature is that they can store objects that have a fixed part and a part that could be anything and it's stored in a dictionary. So the NSManagedObject looks something like this: 
```
    @NSManaged private(set) var property1: String
    @NSManaged private(set) var property2: String
    @NSManaged private(set) var otherParameters: [String : AnyObject]?
```
now, again from JavaScript, they can search and they get back a json array containing all the objects matching the search. And that's where, from the NSManagedObject subclass, I create a JSON class (converting the Dictionary<String, AnyObject> to JSON) and then I need to create a string representing the JSON to pass to the webview `evaluateJavaScript` method.

**Comment by jgallagher** [comment] 2016-02-15 15:47
Sorry, more questions. Is `otherParameters` a Transformable in your Core Data model? How does data get into `otherParameters`? Would it make sense to use a class that wraps a `Freddy.JSON` instead of dictionary? Finally, do you interact with `otherParameters` from Swift, or would `NSJSONSerialization` be a better solution to this problem?

**Comment by lucatorella** [comment] 2016-02-15 15:57
Yes `otherParameters` is a Transformable and it gets its values from the JavaScript passing JSON to the Swift counterpart. There is some interaction from Swift with this `otherParameters` driven by the JavaScript code. This `otherParameters` also is passed as a dictionary to another swift framework. 
Since this dictionary is generally very short, I prefer to have the boilerplate I pointed out above, then use for instance `NSJSONSerialization`. It makes the rest of the code cleaner.

**Comment by mdmathias** [comment] 2016-09-14 18:28
Hi @lucatorella. Are you still looking for assistance on this issue, or can we close it?

**Comment by lucatorella** [comment] 2016-09-28 07:38
Hi, I already have a working solution which is the one from my first comment. It just seems a bit like boilerplate.

**Closed** 2016-09-28 22:28 UTC
Labels: question
